### ISSUE TITLE
Unsuccessful run leaves .URL junk file behind

### ISSUE THREAD

**Issue by fwenzel** [meermanr/TVSeriesRenamer#18]
STR:

```
[~]$ mkdir /tmp/foo

[~]$ cd /tmp/foo

[/tmp/foo]$ tvrenamer.pl 
TV Series Renamer v2.56
Released 24 April 2012
Autodetecting season number failed
Detected series name 'foo' (Season 1 (assumed))
Reading input in AutoFetch mode from EpGuides.com
Fetching document ... 
Can't fetch "http://epguides.com/foo/", please check this URL in a browser
 Consider specifying an URL on the command-line. Error was: 
No useable results. Trying: TV.com
Performing search...
Match = season-1/Found match!
Creating link file in current directory to avoid repeating search...
Unsupported input source: "season-1/"%

[/tmp/foo]$ ls -l
total 8
-rw-r--r--  1 fred  wheel  33 Jan 23 09:24 foo (Season 1) [TV.com].URL

[/tmp/foo]$ 
```

**Comment by fwenzel** [comment]
"Creating link file in current directory to avoid repeating search..." appears to indicate it's a feature, but I am not sure what exactly it helps or why that's good behavior ;)

**Comment by meermanr** [comment]
The bug here is that it thought it found a match for a series called "Foo". 

Yes, it caches the URL so it does not have to repeat the search process. I do consider that a feature, since it avoids unstable results related to flipping between different sites due to updates in `tvrenamer.pl`.

(Once upon a time, updates were frequent enough for this to be a nuisance!)

**Comment by fwenzel** [comment]
Oh I see what you're saying. It would go back and forth between different sources, and thus rename the whole list of files over and over.

Okay yeah I suggest you keep the URL file, *iff* the series was actually found at that source.

When does / doesn't it create that file? I've never seen it.

**Comment by meermanr** [comment]
> When does / doesn't it create that file? I've never seen it.

It is limited to using TV.com mode (which is the fallback when EpGuides.com doesn't have the series). It was added because the search process can do quite a few round-trips to navigate the sites search results and get the data we really want.

During development of this I was hitting TV.com a lot, and was rather shy about the number of requests being made. Perhaps more to the point, their search results were slow to load at the time (10+ seconds), which was annoying me.

EpGuides.com doesn't have this problem, partly because we don't actually search the site at all - we generate a URL and try it. That's pretty quick.

I've not looked at (or used!) this script in years. I'm so embarrassed by the code and its lack of structure. But at least it is commented enough for me to stumble through it.. just about.

If I still maintained offline collections of TV series I would rewrite it in Python, but I lack motivation (and to an extent, opportunity).

**Comment by fwenzel** [comment]
> I've not looked at (or used!) this script in years. I'm so embarrassed by the code and its lack of structure. But at least it is commented enough for me to stumble through it.. just about.

If it's any consolation, release early, release often. The code you ship is better than the project that doesn't see the light of day ;)
